<!--[if !IE]>start section<![endif]-->	
<div class="section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Dashboard</h2>
		<span class="title_wrapper_left"></span>
		<span class="title_wrapper_right"></span>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<div class="sct_left">
				<div class="sct_right">
					<div class="sct_left">
						<div class="sct_right">
							<!--[if !IE]>start dashboard menu<![endif]-->
							<div class="dashboard_menu_wrapper">
							<ul class="dashboard_menu">
								<li><a href="<?= $this->adminUrl(null, 'settings'); ?>" class="d8"><span>Website Settings</span></a></li>	
								<li><a href="<?= $this->adminUrl('edit', 'users'); ?>" class="d1"><span>Add New User</span></a></li>
							</ul>
							</div>
							<!--[if !IE]>end dashboard menu<![endif]-->
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		<!--[if !IE]>start section content bottom<![endif]-->
		<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
		<!--[if !IE]>end section content bottom<![endif]-->
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->