<!--[if !IE]>start wrapper<![endif]-->
	<div id="wrapper">
		<!--[if !IE]>start login wrapper<![endif]-->
		<div id="login_wrapper">
		
			<?php if ($this->failureMessage): ?>
				<div class="error">
					<div class="error_inner">
						<strong>Access Denied</strong> | <span><?= $this->failureMessage; ?></span>
					</div>
				</div>	
			<?php endif; ?>	
			
			<!--[if !IE]>start login<![endif]-->
			<form action ="<?= $this->form->getAction() ?>" 
				  method ="<?= $this->form->getMethod() ?>"
				  id ="<?= $this->form->getId() ?>" 
				  enctype="<?= $this->form->getEnctype() ?>">

				<fieldset>					
					<h1 id="logo"><a href="<?= $this->adminUrl; ?>">vkNgine Administration Panel</a></h1>
					<div class="formular">
						<div class="formular_inner">						
						<label>
							<strong>Username:</strong>
							<span class="input_wrapper">
								<?= $this->form->username; ?>
							</span>
						</label>						
						<label>
							<strong>Password:</strong>
							<span class="input_wrapper">
								<?= $this->form->password; ?>
							</span>
						</label>
						<label class="inline">
							<?= $this->form->remember; ?>
							remember me on this computer
						</label>								
						<ul class="form_menu">
							<li><span class="button"><span><span>Submit</span></span><?= $this->form->submit; ?></span></li>
							<li><a href="javascript:void(0);" onclick="history.go(-1)"><span><span>Back</span></span></a></li>
							<li><a href="#"><span><span>Forgot Pass</span></span></a></li>
						</ul>
						
						</div>
					</div>
				</fieldset>
			</form>
			<!--[if !IE]>end login<![endif]-->
		</div>
		<!--[if !IE]>end login wrapper<![endif]-->
	</div>
	<!--[if !IE]>end wrapper<![endif]-->