			<!--[if !IE]>start sidebar<![endif]-->
			<div id="sidebar">
				<div class="inner">
					<!--[if !IE]>start calendar<![endif]-->
					<div class="calendar">
						<div class="calendar_top">
							<?php 
								$currentTime = new Zend_Date();
								$time = $currentTime->toString(Zend_Date::HOUR) . ':' . $currentTime->toString(Zend_Date::MINUTE);
								$fullDate = $currentTime->toString(Zend_Date::WEEKDAY) . ', ' . date('jS') . ' 
									' . $currentTime->toString(Zend_Date::MONTH_NAME) . ' ' .
									$currentTime->toString(Zend_Date::YEAR);
							?>
							<strong><?= $time; ?></strong>
							<span><?= $fullDate; ?></span>
						</div>
						
						<div class="calendar_bottom"></div>						
					</div>
					<!--[if !IE]>end calendar<![endif]-->
					
					<!--[if !IE]>start section<![endif]-->	
					<div class="section">
						<!--[if !IE]>start quick info<![endif]-->
						<div class="quick_info">
							<div class="quick_info_top">
								<h2>Site information</h2>
							</div>
							<div class="quick_info_content">
							<?php 
								$modelPictures = new Model_Pictures();		
								$modelAlbums = new Model_Albums();						
							?>
								<dl>
									<dt><?= count($modelAlbums->fetchAll());?></dt>
									<dd>total albums</dd>
								</dl>
								<dl>
									<dt><?= $modelPictures->fetchTotals()?></dt>
									<dd>total pictures</dd>
								</dl>	
								<dl>
									<dt>-----</dt>
									<dd>&nbsp;</dd>
								</dl>
								<dl>
									<dt><?= $modelPictures->fetchTotals(2007)?></dt>
									<dd>pictures & <b><?= count($modelAlbums->fetchAlll(2007, 'ALL'));?></b> albums in 2007</dd>
								</dl>							
								<dl>
									<dt><?= $modelPictures->fetchTotals(2008)?></dt>
									<dd>pictures & <b><?= count($modelAlbums->fetchAlll(2008, 'ALL'));?></b> albums in 2008</dd>
								</dl>
								<dl>
									<dt><?= $modelPictures->fetchTotals(2009)?></dt>
									<dd>pictures & <b><?= count($modelAlbums->fetchAlll(2009, 'ALL'));?></b> albums in 2009</dd>
								</dl>
								<dl>
									<dt><?= $modelPictures->fetchTotals(2010)?></dt>
									<dd>pictures & <b><?= count($modelAlbums->fetchAlll(2010, 'ALL'));?></b> albums in 2010</dd>
								</dl>
								<dl>
									<dt><?= $modelPictures->fetchTotals(2011)?></dt>
									<dd>pictures & <b><?= count($modelAlbums->fetchAlll(2011, 'ALL'));?></b> albums in 2011</dd>
								</dl>								
							</div>
							<span class="quick_info_bottom"></span>
						</div>
						<!--[if !IE]>end quick info<![endif]-->
					</div>
					<!--[if !IE]>end section<![endif]-->
					
					<?php if($this->params['action'] == 'email' or $this->params['action'] == 'templates') : ?>
					<!--[if !IE]>start section<![endif]-->	
					<div class="section">
						<!--[if !IE]>start title wrapper<![endif]-->
						<div class="title_wrapper">
							<h2>Templates</h2>
							<span class="title_wrapper_left"></span>
							<span class="title_wrapper_right"></span>
						</div>

						<!--[if !IE]>end title wrapper<![endif]-->
						<!--[if !IE]>start section content<![endif]-->
						<div class="section_content">
							<!--[if !IE]>start section content top<![endif]-->
							<div class="sct">
								<div class="sct_left">
									<div class="sct_right">
										<div class="sct_left">
											<div class="sct_right">
												<ul class="sidebar_menu">
													<li><a href="<?= $this->adminUrl('templates', 'settings'); ?>/mode/registration">Registration emails</a></li>
													<li class="last"><a href="<?= $this->adminUrl('templates', 'settings'); ?>/mode/monthly">Monthly emails</a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</div>

							<!--[if !IE]>end section content top<![endif]-->
							<!--[if !IE]>start section content bottom<![endif]-->
							<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
							<!--[if !IE]>end section content bottom<![endif]-->
							
						</div>
						<!--[if !IE]>end section content<![endif]-->
					</div>
					<!--[if !IE]>end section<![endif]-->	
					<?php endif; ?>				
					
				</div>
			</div>
			<!--[if !IE]>end sidebar<![endif]-->