<?php 
define('IN_DEVELOPMENT', APPLICATION_ENV === 'development');

$this->headLink()->prependStylesheet($this->baseUrl('/css/admin/admin-login.css'));

$this->headScript()->prependFile($this->baseUrl('/js/jquery.min.js'));

echo $this->doctype() . "\n";
?>

<html xmlns="http://www.w3.org/1999/xhtml"> 
<head profile="http://www.w3.org/2005/10/profile"> 

<?php 
	echo $this->headTitle() . "\n";
	echo $this->headMeta()  . "\n";
	echo $this->headLink()  . "\n";
	echo $this->headScript(). "\n";
?>	
	<!--[if lte IE 6]><link media="screen" rel="stylesheet" type="text/css" href="<?= $this->baseUrl('/css/admin/admin-login-ie.css') ?>" /><![endif]-->

	</head>
<body> 		
	
	<?= $this->layout()->content ?>
	  
</body>
</html>


