	<?php 
		$this->headScript()->prependFile($this->baseUrl('/js/admin/logs.js'));
	?>
	
	<script type="text/javascript">
		$(document).ready(function() {			
			disableAllButtons();

			$('#checkAll').bind('click', function() {				
				checkAllCheckbox();				  
			});	

			$('#unCheckAll').bind('click', function() {				
				uncheckAllCheckbox();				
			});
		});		
	</script>
	
	<div id="deleteDialog" title="Delete Log(s)" style="display:none">
		Are you sure you want to delete the selected log(s)?
	</div>	
	
	<div id="detailsDialog" title="Info" style="display:none"></div>
		
	<!--[if !IE]>start section<![endif]-->	
	<div class="section table_section">
		<!--[if !IE]>start title wrapper<![endif]-->
		<div class="title_wrapper">
			<h2>Activity Traffic</h2>
			<span class="title_wrapper_left"></span>
			<span class="title_wrapper_right"></span>
		</div>
		<!--[if !IE]>end title wrapper<![endif]-->

		<!--[if !IE]>start section content<![endif]-->
		<div class="section_content">
			<!--[if !IE]>start section content top<![endif]-->
			<div class="sct">
				<div class="sct_left">
					<div class="sct_right">
						<div class="sct_left">
							<div class="sct_right">
								<!--[if !IE]>start table_wrapper<![endif]-->
								<div class="table_wrapper">
									<div class="table_wrapper_inner">
									<table cellpadding="0" cellspacing="0" width="100%">
										<tbody>
											<tr>	
												<th style="width: 15px;">&nbsp;</th>					
												<th><a href="<?= $this->adminUrl('activity', 'logs', array_merge($this->params, array('orderBy' 	 => 'date', 
																															     	   'orderBySort' => (($this->params['orderBy'] == 'date' && $this->params['orderBySort'] == 'DESC')  ? 'ASC' : 'DESC') ))) ?>" 
													   class="<?= (($this->params['orderBy'] == 'date' && $this->params['orderBySort'] == 'DESC') ? 'desc' : 'asc') ?>">Date of Action</a></th>	
												<th><a href="<?= $this->adminUrl('activity', 'logs', array_merge($this->params, array('orderBy' 	 => 'userId', 
																															     	   'orderBySort' => (($this->params['orderBy'] == 'userId' && $this->params['orderBySort'] == 'DESC')  ? 'ASC' : 'DESC') ))) ?>" 
													   class="<?= (($this->params['orderBy'] == 'userId' && $this->params['orderBySort'] == 'DESC') ? 'desc' : 'asc') ?>">User ID</a></th>		   												   
												<th><a href="<?= $this->adminUrl('activity', 'logs', array_merge($this->params, array('orderBy' 	 => 'description', 
																															     	   'orderBySort' => (($this->params['orderBy'] == 'description' && $this->params['orderBySort'] == 'DESC')  ? 'ASC' : 'DESC') ))) ?>"
													   class="<?= (($this->params['orderBy'] == 'description' && $this->params['orderBySort'] == 'DESC') ? 'desc' : 'asc') ?>">Description</a></th>
												<th><a href="<?= $this->adminUrl('activity', 'logs', array_merge($this->params, array('orderBy' 	 => 'module', 
																															     	 'orderBySort' => (($this->params['orderBy'] == 'module' && $this->params['orderBySort'] == 'DESC')  ? 'ASC' : 'DESC') ))) ?>" 
													   class="<?= (($this->params['orderBy'] == 'module' && $this->params['orderBySort'] == 'DESC') ? 'desc' : 'asc') ?>">Module</a></th>										   
												<th><a href="<?= $this->adminUrl('activity', 'logs', array_merge($this->params, array('orderBy' 	 => 'action', 
																															     	 'orderBySort' => (($this->params['orderBy'] == 'action' && $this->params['orderBySort'] == 'DESC')  ? 'ASC' : 'DESC') ))) ?>" 
													   class="<?= (($this->params['orderBy'] == 'action' && $this->params['orderBySort'] == 'DESC') ? 'desc' : 'asc') ?>">Action</a></th>
												<th><a href="<?= $this->adminUrl('activity', 'logs', array_merge($this->params, array('orderBy' 	 => 'permission', 
																															     	   'orderBySort' => (($this->params['orderBy'] == 'permission' && $this->params['orderBySort'] == 'DESC')  ? 'ASC' : 'DESC') ))) ?>" 
													   class="<?= (($this->params['orderBy'] == 'permission' && $this->params['orderBySort'] == 'DESC') ? 'desc' : 'asc') ?>">Permission</a></th>	   															
											</tr>
										<?php 
											if (count($this->logs)):
												foreach($this->logs as $log) :	
										?>
											<tr>
												<td>	
													<input class="radio deleteSingle" name="logs[]" type="checkbox" value="<?= $log->activityId; ?>" />
												</td>
												<td><?= $this->escape($this->dateFormat($log->date, true, true)) ?></td>
												<td><?= $this->escape($log->userId); ?></td>
												<td><?= $this->escape($log->description); ?></td>
												<td><?= $this->escape($log->module); ?></span></td>
												<td><?= $this->escape($log->action); ?></td>
												<td><?= $this->escape($log->permission); ?></td>
											</tr>											
											<?php endforeach; ?>
												
										<?php else: ?>
												
										<?php endif; ?>
										
									</tbody></table>
									</div>

								</div>
								<!--[if !IE]>end table_wrapper<![endif]-->
								
								<!--[if !IE]>start table menu<![endif]-->
								<div class="table_menu">									
									<ul class="right">
										<li><a href="javascript:void(0);" id="checkAll" class="button selectAll enabled"><span><span>CHECK ALL</span></span></a></li>
										<li><a href="javascript:void(0);" id="unCheckAll" class="button unselectAll" ><span><span>UNCHECK ALL</span></span></a></li>	
										<li><a href="javascript:void(0);" id="deleteAll" class="button deleteAll" onclick="showDeleteLogsDialog('<?= $this->params['action']?>');" ><span><span>DELETE</span></span></a></li>						
									</ul>
								</div>
								<!--[if !IE]>end table menu<![endif]-->
								
								<?= $this->paginationControl($this->logs, 'Sliding', 'logs/paginator.phtml'); ?>								
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--[if !IE]>end section content top<![endif]-->
			<!--[if !IE]>start section content bottom<![endif]-->
			<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>

			<!--[if !IE]>end section content bottom<![endif]-->
			
		</div>
		<!--[if !IE]>end section content<![endif]-->
	</div>
	<!--[if !IE]>end section<![endif]-->
	