<?php 
	$this->headScript()->prependFile($this->baseUrl('/js/admin/templates.js'));
?>

<div id="editTemplate" style="display:none" title="Edit Template"></div>
<div id="previewTemplateDialog" style="display:none" title="Live Preview"></div>
	
<!--[if !IE]>start section<![endif]-->	
<div class="section table_section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">
		<h2>Templates</h2>
		<span class="title_wrapper_left"></span>
		<span class="title_wrapper_right"></span>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->
		<div class="sct">
			<div class="sct_left">
				<div class="sct_right">

					<div class="sct_left">
						<div class="sct_right">
							
							<div  id="product_list">
							<!--[if !IE]>start table_wrapper<![endif]-->
							<div class="table_wrapper">
								<div class="table_wrapper_inner">
								<table cellpadding="0" cellspacing="0" width="100%">
									<tbody><tr>						
										<th>Type</th>									
										<th><a href="#" class="asc">Subject</a></th>
										<th>Actions</th>
									</tr>
									<?php 
										if (count($this->templates)):
											foreach($this->templates as $template) :													
									?>
									<tr class="first">
										<td style="width: 125px;"><?= $this->escape($template['explain'])?></td>
										<td><a href="javascript:void(0);" ref="<?= $template->templateId?>" class="editTemplate product_name"><?= $this->escape($template['subject'])?></a></td>	
																								
										<td style="width: 120px;">
											<div class="actions_menu">
												<ul>
													<li><a href="javascript:void(0);" ref="<?= $template->templateId?>" class="previewTemplate sm3">Preview</a></li>
												</ul>
											</div>
										</td>
									</tr>
										<?php endforeach; ?>
							
									<?php else: ?>	
											No template(s) found
									<?php endif; ?>
								</tbody></table>
								</div>
							</div>
							<!--[if !IE]>end table_wrapper<![endif]-->
							</div>
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		<!--[if !IE]>start section content bottom<![endif]-->

		<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
		<!--[if !IE]>end section content bottom<![endif]-->
		
	</div>
	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->
					
<script type="text/javascript">
	$('.editTemplate').bind('click', function() {				
		editTemplate($(this).attr('ref'), '<?= $this->params['mode']?>');	
	});
	
	$('.previewTemplate').bind('click', function() {				
		previewTemplate($(this).attr('ref'));	
	});	

	
</script>