<!-- Main -->
   			 <div id="main" class="expandheight">
   			 	
      			<h2 class="section_title">About us</h2>
      				
      				<div id="content" class="content_full_width">
      				    <div class="two_thirds">
	      				    <h3>Jennifer Yavuz says...</h3>
							    <blockquote>To be filled in :)</blockquote>
						</div>							
						<div class="one_third right">
							<h3>We are...</h3>    
						        <ul class="contact_list">
						            <li class="contact_phone">Volkan Yavuz</li>
						            <li class="contact_email"><a href="mailto:vnj@vknyvz.com">vnj@vknyvz.com</a></li>
						            <li class="contact_address">666 One Way vkn Street, NY</li>
						        </ul>
						        <img src="/images/map.jpg" alt="map" class="map" />
						</div>	 	
					</div>					  
              		<!-- Content ends here --> 
      
      		</div>
      		<!-- Main ends here --> 