<!-- Main 
   			 <div id="main">
   			 	
      			<h2 class="section_title">Welcome to Volkan and Jennifer Yavuz [dot]com</h2>
      				
      				 Content - full width (class="content_full_width") 
      				<div id="content" class="content_full_width">
      
						    <h3>Volkan Yavuz says...</h3>
						     
							    <blockquote>Please use a modern browser to view this site. <br> Check below for more details.</blockquote>
							    
							    <h4>Minium system requirements:</h4>
							    	Internet Explorer 7 or 8 <br>
							    	Firefox 3.6.16 <br>
							    	Google Chrome 10.0 <br>
							    	Safari 5.0.4 <br><br>
							    
							    <h4>Recommended</h4>
							    	I recommend you to use Firefox 4 or latest version of Google Chrome <br>
							    	
							    <h4>Not supported</h4>
							    	Internet Explorer 9 <br>
							    	Firefox any version below 3.5 <br>
							    	Google Chrome any version below 10.0 <br>
							    	Safari any version below 5.0 <br>
						
							  </div> 
							  
              		 Content ends here  
      
      		</div>
      		 Main ends here  -->