<!--[if !IE]>start section<![endif]-->	
<div class="section">
	<!--[if !IE]>start title wrapper<![endif]-->
	<div class="title_wrapper">

		<h2>User Management</h2>
		
		<span class="title_wrapper_left"></span>
		<span class="title_wrapper_right"></span>
	</div>
	<!--[if !IE]>end title wrapper<![endif]-->
	<!--[if !IE]>start section content<![endif]-->
	<div class="section_content">
		<!--[if !IE]>start section content top<![endif]-->

		<div class="sct">
			<div class="sct_left">
				<div class="sct_right">
					<div class="sct_left">
						<div class="sct_right">
							
							<h3><?= $this->userId ? 'Edit' : 'Add New'; ?> User <?= $this->userId ? '#'.$this->userId : ''; ?></h3>
							
							<?= ((count($this->errors) > 0) ? $this->partial('msg_error.phtml', array('errors' => $this->errors)) : ''); ?>
							<?= (!empty($this->infoMessage) ? $this->partial('msg_info.phtml', array('message' => $this->infoMessage)) : '') ?>
							
							<?= $this->form; ?>					
							
						</div>

					</div>
				</div>
			</div>
		</div>
		<!--[if !IE]>end section content top<![endif]-->
		<!--[if !IE]>start section content bottom<![endif]-->
		<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
		<!--[if !IE]>end section content bottom<![endif]-->
		
	</div>

	<!--[if !IE]>end section content<![endif]-->
</div>
<!--[if !IE]>end section<![endif]-->