	<?php 
		$this->headScript()->prependFile($this->baseUrl('/js/admin/pictures.js'));
		$this->headScript()->prependFile($this->baseUrl('/js/admin/facebox/facebox.js'));
		
		$this->headLink()->prependStylesheet($this->baseUrl('/js/admin/facebox/facebox.css'));			
	?>
	
	<script type="text/javascript">
		$(document).ready(function() {		
			$('a[rel*=facebox]').facebox({
		        loadingImage : '<?= $this->baseUrl('/js/admin/facebox/loading.gif')?>',
		        closeImage   : '<?= $this->baseUrl('/js/admin/facebox/closelabel.png')?>'
		      })
		    })	  
	</script>

	<!--[if !IE]>start section<![endif]-->	
	<div class="section table_section">
		<!--[if !IE]>start title wrapper<![endif]-->
		<div class="title_wrapper">
			<h2>Album Management - <?= $this->escape($this->albumName); ?></h2>
			<span class="title_wrapper_left"></span>
			<span class="title_wrapper_right"></span>
		</div>
		<!--[if !IE]>end title wrapper<![endif]-->

		<!--[if !IE]>start section content<![endif]-->
		<div class="section_content">
			<!--[if !IE]>start section content top<![endif]-->
			<div class="sct">
				<div class="sct_left">
					<div class="sct_right">
						<div class="sct_left">
							<div class="sct_right">
								
								<form action="/albums/browse" method="post" id="saveAlbumDescription">

								<fieldset>
								<!--[if !IE]>start table_wrapper<![endif]-->
								<div class="table_wrapper">
									<div class="table_wrapper_inner">
									<table cellpadding="0" cellspacing="0" width="100%">
										
											<tr>						
												<th style="width: 15px;"><a href="">ID#</a></th>													   
												<th><a href="">Thumbnail Name</a></th>
												<th><a href="">View Count</a></th>		
												<th style="width:65%" >Description</th>										
											</tr>
										<?php 
											if (count($this->pictures)):
												foreach($this->pictures as $picture) :													
										?>
											<tr>
												<td><?= $picture->pictureId; ?></td>
												<td><a href="<?= '/_dB/' . $picture['albumId'] . '/' . $picture->thumbnailName; ?>" rel="facebox"><?= $picture->thumbnailName; ?></a></td>
												<td><?= $this->escape($picture->count); ?></td>
												<td><input type="text=" style="width:100%" name="pictureDescription[<?= $picture->pictureId; ?>]" value="<?= $picture->pictureDescription; ?>">
											</tr>											
											<?php endforeach; ?>
												
										<?php else: ?>
												
										<?php endif; ?>
										
									</table>
									</div>
									<div class="row">

								</div>
								<!--[if !IE]>end table_wrapper<![endif]-->
												
								<!--[if !IE]>start table menu<![endif]-->
								<div class="table_menu">									
									<div class="buttons buttonsSubmit save">
										<ul>
											<li class="list_no_item">
												<span class="button send_form_btn"><span>
												<span>Save</span></span>
													<input type="submit" helper="formSubmit" value="" id="submit" name="submit">
												</span>
											</li>
										</ul>
								   </div>
								</div>
								<!--[if !IE]>end table menu<![endif]-->
																
								</fieldset>
								
								</form>
								
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--[if !IE]>end section content top<![endif]-->
			<!--[if !IE]>start section content bottom<![endif]-->
			<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>

			<!--[if !IE]>end section content bottom<![endif]-->
			
		</div>
		<!--[if !IE]>end section content<![endif]-->
	</div>
	<!--[if !IE]>end section<![endif]-->