<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/login.js'));
?>

			<!-- Main -->
   			 <div id="main">
   			 	
      			<h2 class="section_title">Login</h2>
      				
      				<div id="content" class="content_full_width">
      				
      				<div class="two_thirds">
      					<p>&nbsp;</p>
      					
						<?= $this->form; ?>
						
						<div id="login-errors"></div>
						
						<div class="vkNgine-copyright">
							Powered by vkNgine &copy 2011 <br>
							This application was written by <a href="mailto:vkn@vknyvz.com">Volkan Yavuz</a>. <br> 
						</div>
						
					</div>
					
              </div>  
      		<!-- Content ends here -->
      		</div>
      		<!-- Main ends here -->
